### ISSUE TITLE
Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by edward-at-intelex** [nitaliano/react-native-mapbox-gl#297]
Hello - I searched the issues here as well as in stackOverflow, but cannot seem to find a resolution to this problem.

I followed the _manual_ instructions - [https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md](url) - to install react-native-mapbox-gl for iOS, installing manually onto my Macbook Pro and I am using_ xCode 7.2.x_ . 

I am getting an error in xCode and the project fails to build with the following error :

```
ld: framework not found Mapbox
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

xCode is executing the following command:

```
Ld /Users/edward/Library/Developer/Xcode/DerivedData/rnp3-bmfxgzpqxxodcqfrgjyuxbsnajtz/Build/Products/Debug-iphonesimulator/rnp3.app/rnp3 normal i386

    cd /Users/edward/gitRepo/someProject/ios

    export IPHONEOS_DEPLOYMENT_TARGET=8.0

    export PATH="(extremely long path statement)"

-v
```

general details - 
*running react-native 0.2x (latest) 
*used node 4.x stable to install react-native-mapbox-gl via npm
*Also changed the deployment target from iOS 7.x to 8.x and 9.x in xCode and still get the same results. 

initial thought - do I have to add some file or folder to path? let me know.

Any help is appreciated. thanks - Edward

**Comment by bsudekum** [comment]
Any chance you could post a screenshot of your Xcode setup? Can you verify you added the Mapbox framework in the embedded framework section?

**Comment by edward-at-intelex** [comment]
@bsudekum thanks for responding. I will post a screenshot of xCode setup in a moment but yes I embedded the Mapbox framework in the embedded framework settings under the General Tab for my project.

In the meantime, I thought I would follow up with the following:

1) looks like the process for creating Android version works (I was able to implement the example)
2) I also attempted the cocoapods install. Got a similar linker error  - 

`ld: library not found for -lPods-{projectName}
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

(even going further as to add the additional references to my podfile as you described further on in the iOS instructions and updating the node_modules references appropriately, this executed with no errors) 
`
source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'projectName'
workspace 'projectName'

pod 'RCTMapboxGL', :path => '../node_modules/react-native-mapbox-gl/ios'
pod 'React', :path => '../node_modules/react-native'
pod 'React/RCTGeolocation', :path => '../node_modules/react-native'
pod 'React/RCTImage', :path => '../node_modules/react-native'
pod 'React/RCTNetwork', :path => '../node_modules/react-native'
pod 'React/RCTText', :path => '../node_modules/react-native'
pod 'React/RCTWebSocket', :path => '../node_modules/react-native'
`

So having tried both methods on two mac machines I am currently stuck.

**Comment by edward-at-intelex** [comment]
Here is the general order of steps I performed in image form as per your request @bsudekum 
1. install at command prompt
   ![mb001_install](https://cloud.githubusercontent.com/assets/16785088/13582530/da37a16a-e47a-11e5-904f-e615d52065fe.png)
2. add to project
   ![mb002_setup](https://cloud.githubusercontent.com/assets/16785088/13582531/dd25396e-e47a-11e5-8594-fd8f1412aef8.png)
3. embed in general tab
   ![mb003_embedbinary_ingeneral](https://cloud.githubusercontent.com/assets/16785088/13582535/e164a26c-e47a-11e5-9418-26dd0f2d4e87.png)
4. add run script in build phase
   ![mb004_addbashscript](https://cloud.githubusercontent.com/assets/16785088/13582539/e39066a2-e47a-11e5-805f-552ac01389ef.png)
5. add framework/library
   ![mb005_addlibrctmapbox](https://cloud.githubusercontent.com/assets/16785088/13582545/eb54bab4-e47a-11e5-86ad-582fc4f713de.png)
6. result of adding framework/library
   ![mb006_addlinkbinary](https://cloud.githubusercontent.com/assets/16785088/13582547/ecfb2880-e47a-11e5-88ec-fb64153fba3e.png)

I then implemented the example and built the project in Xcode.

**Comment by edward-at-intelex** [comment]
Here was the result (from one of a number of multiple tests) @bsudekum  ...

![screen shot 2016-03-07 at 3 51 56 pm](https://cloud.githubusercontent.com/assets/16785088/13583111/acd8b418-e47d-11e5-8116-2c83d6a37f8e.png)

specs:
*xCode 7.2.1
*simulator was set up as iphone5 / iOS 8.1,9.1,9.2 or iPhone 6s iOS 8.1,9.1,9.2
*fresh install for examples: npm / nvm, node 4.x, react-native 0.20 (they have since upgraded to 0.21)
*I am the admin of my machine with root access (if required)

I also ran the setup against cocoa pods (latest version) and had the native version of Ruby for OSX (I think 2.x) then upgraded to the latest version for OSX.

_notes: in a test I performed today (March 7th, over a week later) I was able to get the example iOS app running by launching the site from the *_terminal*\*  using the command`react-native run-ios` !!! but not in xCode on two different machines??
*\* I also noted that the manual instructions for iOS do not necessarily match the images provided , had to infer whether to add "bash" to the run script command for example, or when you right-click on your project to add files, do you add the RCTMapbox.xpcodeproj to the root of your project or in the libraries folder? - The choice you make determines whether xCode finds Mapbox.framework easily or not when you embed it in the general tab and it _may_ be the cause of some issues (xCode might not find it on building the project and the icon indicates its 'missing') 

![mb007_gotittoworkatcommandprompt](https://cloud.githubusercontent.com/assets/16785088/13583388/090a9b10-e47f-11e5-8c1b-faac608ed28c.png)

**Comment by frankbolviken** [comment]
I'm getting the same issue. Been following the guide for adding to Xcode manually, but getting the 
framework not found Mapbox when trying to build the application.

**Comment by frankbolviken** [comment]
My problem was that I initially did one of the steps wrong (added a library to the wrong path), and no matter if I fixed it it was broken.
Had to recreate the whole project, then it worked fine.

**Comment by edward-at-intelex** [comment]
@frankbolviken so even just removing and re-adding the correct library and its path did not work for you? re-creating the entire project? strange, I will try.

**Comment by tharrington** [comment]
@edward-at-intelex  did you solve this problem?

**Comment by digitaldavenyc** [comment]
I am experiencing the same issue. I have followed the guide exactly but still receive the error

```
ld: framework not found Mapbox
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dmiskiew** [comment]
I added following entry to `Build Settings -> Framework Search Paths` (Debug and Release) and it solved the problem on my machine:
`$(PROJECT_DIR)/../node_modules/react-native-mapbox-gl` (recursive)

![screenshotmapbox](https://cloud.githubusercontent.com/assets/159009/18593268/f2235d98-7c3a-11e6-99c3-67592607012c.png)

**Comment by ghost** [comment]
Any update on this, I seem to be getting the same error `framework not found Mapbox` 

Most recent post https://github.com/mapbox/react-native-mapbox-gl/pull/741

Seem to have tried many approaches, both via CocoaPods and Manual installation ... neither is currently working for me. 

When doing CocoaPods, I get `framework not found Mapbox`, when doing manual install I get issues such as `framework not found XCTest`

After removing the project, cloning again, running npm install, and jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js clustr_app/node_modules/ on my project node modules, I then get the following after the app starts up which is libc++abi.dylib: terminating with uncaught exception of type NSException (lldb)

Thanks very much

**Comment by cglacet** [comment]
I have the same problem, my installation used to work, then I followed [this procedure to add facebook login support](https://developers.facebook.com/docs/react-native/configure-ios) and I think it broke something but I don't know what.

**Comment by jamonholmgren** [comment]
I was able to solve it with @dmiskiew's fix, but had a slightly different URL due to installing mapbox-gl from the scoped package:

```
$(PROJECT_DIR)/../node_modules/@mapbox/react-native-mapbox-gl
```
