### ISSUE TITLE
Build failed due to 'Mapbox/Mapbox.h' file not found

### ISSUE THREAD

**Issue by ds3783** [nitaliano/react-native-mapbox-gl#350]
After project configuration changing, which I followed installation guide, the project could't build. 
Error message as follows:

~/Projects/my/AwsomeApp/node_modules/react-native-mapbox-gl/ios/RCTMapboxGL/RCTMapboxGL.h:9:9: 'Mapbox/Mapbox.h' file not found

~/Projects/my/AwsomeApp/node_modules/react-native-mapbox-gl/ios/RCTMapboxGL/RCTMapboxGL.m:9:9: In file included from ~/Projects/my/AwsomeApp/node_modules/react-native-mapbox-gl/ios/RCTMapboxGL/RCTMapboxGL.m:9:

**Comment by jayfunk** [comment]
What do you mean by configuration changing? Is the mapbox.h file actually
there? Did you update mapbox?

**Comment by ds3783** [comment]
I followed installation manual,but my project couldn't compile

https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md

my mapbox sdk is 3.2.0

**Comment by yutin1987** [comment]
+1
I follow this step:
https://www.mapbox.com/ios-sdk/#manual

**Comment by yutin1987** [comment]
This issue occurs when npm install is failed (run download-mapbox-gl-native-ios.sh is failed).
ref. #366

**Comment by yutin1987** [comment]
You can try reinstall

```
npm uninstall react-native-mapbox-gl --save
npm install react-native-mapbox-gl --save
```

**Comment by dapetcu21** [comment]
True, the installation documentation needs to be updated to include adding Mapbox to embedded binaries.

**Comment by digitaldavenyc** [comment]
+1 for this issue

**Comment by 1ec5** [comment]
Via #402 and #417, the CocoaPods installation method doesn’t automatically link Mapbox.framework correctly either.

**Comment by ghost** [comment]
Jup, I have the same problem, any fix??

**Comment by ghost** [comment]
DONE!

Download the Framework from this Link.

http://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-3.3.4-dynamic.zip

Unzip this and copy Mapbox.framework in following folder:

**$app_path**/node_modules/react-native-mapbox-gl/ios

So that the folder looks like this:
<img width="298" alt="mapbox" src="https://cloud.githubusercontent.com/assets/15894713/19474762/4c0c725e-9531-11e6-8311-c03a4de0062b.png">

Then follow the description here:
https://github.com/mapbox/react-native-mapbox-gl/blob/master/ios/install.md

The error Mapbox/Mapbox.h will be fixed.
Have fun with your app and Mapbox :)

**Comment by vjpr** [comment]
@alexanderniebuhr This did not work for me.

What version of `react-native-mapbox-gl` are you running?

I am running `react-native-mapbox-gl@5.0.0` and inside the `package.json` is

```
    "preinstall": "node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 3.3.1",
```

The latest prebuilt is 3.3.4 from https://www.mapbox.com/ios-sdk/. This didn't fix my problem.

```
├─┬ react@15.3.2
│ ├── fbjs@0.8.5
│ ├── loose-envify@1.2.0
│ └── object-assign@4.1.0
├─┬ react-native@0.34.1
```

I'm having this error:

```
  "_convertToMGLAnnotation", referenced from:
      ___65-[RCTMapboxGLManager spliceAnnotations:deleteAll:toDelete:toAdd:]_block_invoke in libRCTMapboxGL.a(RCTMapboxGLManager.o)
  "_imageFromSource", referenced from:
      -[RCTMapboxGL mapView:imageForAnnotation:] in libRCTMapboxGL.a(RCTMapboxGL.o)
ld: symbol(s) not found for architecture x86_64
```

Seems like `Mapbox.framework` 3.3.1 and 3.3.4 are not compatible with `react-native-mapbox-gl@5.0.0` (`ios/RCTMapboxGL`)?

Here is the linker command that is failing:

```



/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-arch
x86_64
-isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.0.sdk
-L/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator
-L/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/JTSImageViewController
-L/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/RCTMapboxGL
-L/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/React
-F/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator
-F/Users/Vaughan/dev-live/xxx/ios/Pods/../../node_modules/react-native-mapbox-gl/ios
-F/Users/Vaughan/dev-live/xxx/ios
-filelist
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Intermediates/ting.build/Debug-iphonesimulator/ting.build/Objects-normal/x86_64/ting.LinkFileList
-Xlinker
-rpath
-Xlinker
@executable_path/Frameworks
-mios-simulator-version-min=8.0
-Xlinker
-object_path_lto
-Xlinker
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Intermediates/ting.build/Debug-iphonesimulator/ting.build/Objects-normal/x86_64/ting_lto.o
-Xlinker
-no_deduplicate
-Xlinker
-objc_abi_version
-Xlinker
2
-fobjc-arc
-fobjc-link-runtime
-ObjC
-lJTSImageViewController
-lRCTMapboxGL
-lReact
-lstdc++
-framework
Accelerate
-framework
ImageIO
-framework
JavaScriptCore
-framework
Mapbox
-framework
UIKit
-ObjC
-lc++
-lRCTMapboxGL
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libReact.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTImage.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTLinking.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTNetwork.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTSettings.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTText.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTVibration.a
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a
-lPods-ting
-Xlinker
-dependency_info
-Xlinker
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Intermediates/ting.build/Debug-iphonesimulator/ting.build/Objects-normal/x86_64/ting_dependency_info.dat
-o
/Users/Vaughan/Library/Developer/Xcode/DerivedData/ting-dmrsedpvmrstcidoumeaigdkbtfn/Build/Products/Debug-iphonesimulator/ting.app/ting
```

**Comment by vjpr** [comment]
So it appears `RCTMapboxGLConversions.h` is missing from the podspec module.

`RCTMapboxGL.podspec`:

```
  s.source_files = "RCTMapboxGL/RCTMapboxGL.{h,m}", "RCTMapboxGL/RCTMapboxGLManager.{h,m}"
```

Simple fix:

```
  s.source_files = "RCTMapboxGL/RCTMapboxGL.{h,m}", "RCTMapboxGL/RCTMapboxGLManager.{h,m}", "RCTMapboxGL/RCTMapboxGLConversions.{h,m}"
```

Thanks to a clue from @dapetcu21 in https://github.com/mapbox/react-native-mapbox-gl/issues/390

**Comment by ghost** [comment]
Latest. What is the error? Did you follow my instructions?

**Comment by ghost** [comment]
Please try to do a clean reinstall with my instructions 

Kind regards
Alex

**Comment by tmcw** [comment]
Fixed in #455
