### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by iSimar** [nitaliano/react-native-mapbox-gl#68]
Hello there,

After installing the component, decided to run the Example Code (https://github.com/mapbox/react-native-mapbox-gl/blob/master/example.js). 

Map doesn't seem to be loading even though I have placed an accessToken.

Thanks,

Screenshot: 
![img](http://i58.tinypic.com/6i9n9k.png)

**Comment by bsudekum** [comment]
Are there any errors in the console in Xcode? Can you also try another style like dark-v7?

**Comment by iSimar** [comment]
Hey thanks for the quick reply. 
ye it works with other styles expect the 'mapbox-streets-v7' style.

**Comment by bsudekum** [comment]
Per discussion with @1ec5, [these 2 lines need to be switched](https://github.com/mapbox/react-native-mapbox-gl/blob/b593541ba1ac34332012738abd03ab3909a95dfd/RCTMapboxGL/RCTMapboxGL.m#L94-L95). @iSimar for now you reverse these locally until a new release is put out to fix this issue.

**Comment by iSimar** [comment]
Thanks for all your help!

**Comment by jackbillstrom** [comment]
I'm facing the same problem, here's how my emulator looks. I'm using the `emerald-style` on my map but it's still blank, and I'm also using default secret token from MapBox.

@bsudekum Reverse [these](https://github.com/mapbox/react-native-mapbox-gl/blob/master/RCTMapboxGL/RCTMapboxGL.m#L94-L95) lines? Not so good at understanding I'm afraid. 

@1ec5  @iSimar Could you help?

![ios simulator screen shot 23 jul 2015 14 35 29](https://cloud.githubusercontent.com/assets/1582303/8850424/4ce8f128-3148-11e5-8bc2-027157772d45.png)

**Comment by 1ec5** [comment]
@jackbillstrom, the bug here is that the access token is being set after the map view is initialized. If you modify that file by swapping the two highlighted lines, the bug originally reported here should be fixed. @bsudekum, can you try that out and push the fix?

**Comment by jackbillstrom** [comment]
@1ec5 I've changed those lines now, cleaned, rebuilt and run. Now this is being printed in my Xcode terminal:

`"Warning: Native component for "RCTMapboxGL" does not exist"`

The package is installed, I'm not getting those "redscreens" and such. Is this package working with `react-native ^0.7.0` ?

**Comment by bsudekum** [comment]
@jackbillstrom is this a clean install or an upgrade? Can you try:
- cleaning the build
- Make sure you've added the `RCTMapboxGL.xcodeproj` to your build
- delete your `node_modules`  folder and `npm install` again

**Comment by jackbillstrom** [comment]
@bsudekum It's a clean install, tried the things above and I am still getting this in my debugger: 

`Warning: Native component for "RCTMapboxGL" does not exist`

**Comment by Luukschoen** [comment]
@bsudekum I have the same issue as @iSimar . I started a clean react native app with a tabbed interface. After following all installation steps I see the exact same issue as mentioned above. I can see the markers, but just no map. I tried to switch the lines, but it doesn't seem to matter. Only explicitly setting the style url to light or dark will fix it, but I wasn't going to use those layers. Any idea? Console says this:

2015-07-31 18:17:24.425 [info][tid:com.facebook.React.JavaScript] { zoom: 0.02236781302845451, longitude: 0, latitude: 0 }
2015-07-31 18:17:24.533 BookSearch[7760:136559] [ERROR] {Map}[Style]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]:

**Comment by 1ec5** [comment]
@Luukschoen, that comment is out of date: the lines have already been switched as of version 0.4.0 of this component. What version of iOS are you running this on?

**Comment by Luukschoen** [comment]
thought so. Version of  iOS 8.4. React version 0.8.0 and version 0.4.0 of this component.

**Comment by bsudekum** [comment]
@Luukschoen Can you try changing the style to `dark-v7.json`? Also, can you verify that you are specifying an access token?

**Comment by Luukschoen** [comment]
Yes, i can verify that i'm providing a valid access token. That doesn't seem to be the issue. Furthermore, dark and light styles are working correct. So it's the other map layers that don't work oddly enough. I would also like to say that I really like your work on this component guys, keep it up!

**Comment by christocracy** [comment]
Same issue as @Luukschoen.  No tiles loaded for `styleURL={'asset://styles/mapbox-streets-v7.json'}`.  `dark-v7.json` works.
- react-native: 0.8.0
- react-native-mapbox-gl: 0.4.0

**Comment by olliebrennan** [comment]
I am experiencing this issue too.  React-native 0.8.0 & react-native-mapbox-gl: 0.4.0

My API key is valid. I seem unable to get the dark theme working though.

**Comment by christocracy** [comment]
This works for now, I don't know why.  I didn't update anything.

`styleURL={'asset://styles/mapbox-streets-v7.json'}`

**Comment by edcs** [comment]
I'm having similar issues here, my map rendering code is pretty simple at the moment and this snippet works:

``` javascript
render() {
    return (
        <MapboxGLMap
            style={styles.map}
            accessToken={'token'}
            styleURL={'asset://styles/dark-v7.json'}
        />
     );
 }
```

However if I use any of the other available styles, like `styleURL={'asset://styles/mapbox-streets-v7.json'}`, then I get an error in XCode like this:

```
[ERROR] {Map}[Style]: Failed to load [mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6]: 
```

Any ideas?
